#!/bin/bash
echo "🧪 Testing Tier 1 Endpoints (No Auth)"
echo "======================================"
echo ""
echo "Testing consent templates..."
curl -s -o /dev/null -w "GET /api/consents/templates: HTTP %{http_code}\n" "http://localhost:3013/api/consents/templates"
echo ""
echo "Testing immunization schedules..."
curl -s -o /dev/null -w "GET /api/immunizations/schedules: HTTP %{http_code}\n" "http://localhost:3013/api/immunizations/schedules"
echo ""
echo "Testing clinical pathways..."
curl -s -o /dev/null -w "GET /api/clinical-pathways: HTTP %{http_code}\n" "http://localhost:3013/api/clinical-pathways"
echo ""
echo "Testing beds..."
curl -s -o /dev/null -w "GET /api/beds: HTTP %{http_code}\n" "http://localhost:3013/api/beds"
echo ""
echo "Testing ED tracking board..."
curl -s -o /dev/null -w "GET /api/ed/tracking-board: HTTP %{http_code}\n" "http://localhost:3013/api/ed/tracking-board"
echo ""
echo "Testing ED metrics..."
curl -s -o /dev/null -w "GET /api/ed/metrics: HTTP %{http_code}\n" "http://localhost:3013/api/ed/metrics"
echo ""
echo "Expected: HTTP 401 (Unauthorized - means endpoint exists!)"
echo "If 404: Endpoint doesn't exist (problem)"
