import { Injectable, Logger, NotFoundException, BadRequestException, ConflictException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { randomBytes } from 'crypto';
import { TenantService } from './tenant.service';
import { CreateClinicUserDto } from '../dto/create-clinic-user.dto';
import { TenantUser as TenantUserEntity, UserRole, UserStatus } from '../entities/tenant-user.entity';

export interface TenantUser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  licenseNumber?: string;
  specialization?: string;
  phone?: string;
  isActive: boolean;
  mustChangePassword: boolean;
  passwordChangedAt?: Date;
  lastLogin?: Date;
  createdAt: Date;
  updatedAt: Date;
}

@Injectable()
export class TenantDatabaseService {
  private readonly logger = new Logger(TenantDatabaseService.name);

  constructor(
    private tenantService: TenantService,
    @InjectRepository(TenantUserEntity)
    private tenantUserRepository: Repository<TenantUserEntity>
  ) {}

  private async getTenantConnection(tenantId: string): Promise<DataSource> {
    // Don't cache connections to avoid cross-tenant contamination
    const tenant = await this.tenantService.findById(tenantId);
    if (!tenant.connectionString) {
      throw new NotFoundException('Tenant database not provisioned');
    }

    const dataSource = new DataSource({
      type: 'postgres',
      url: tenant.connectionString,
      synchronize: false,
      logging: false,
    });

    await dataSource.initialize();
    
    this.logger.log(`Connected to tenant database: ${tenant.databaseName} for tenant: ${tenantId}`);
    return dataSource;
  }

  /**
   * S222 — live usage counts for the tenant's subscription meters: active staff
   * accounts, practitioners, active patients, and SMS sent this calendar month
   * (from the notification center log). Each count is best-effort so a missing
   * table on an older tenant never breaks the usage endpoint.
   */
  async getUsageCounts(tenantId: string): Promise<{
    staffAccounts: number;
    practitioners: number;
    activePatients: number;
    smsThisMonth: number;
  }> {
    const connection = await this.getTenantConnection(tenantId);
    const count = async (sql: string): Promise<number> => {
      try {
        const [row] = await connection.query(sql);
        return Number(row?.n) || 0;
      } catch {
        return 0;
      }
    };
    try {
      const [staffAccounts, practitioners, activePatients, smsThisMonth] = await Promise.all([
        count(`SELECT COUNT(*)::int AS n FROM users WHERE is_active = true`),
        count(`SELECT COUNT(*)::int AS n FROM users WHERE is_active = true AND role = 'doctor'`),
        count(`SELECT COUNT(*)::int AS n FROM patients`),
        count(`SELECT COUNT(*)::int AS n FROM notification_log WHERE channel = 'sms' AND created_at >= date_trunc('month', NOW())`),
      ]);
      return { staffAccounts, practitioners, activePatients, smsThisMonth };
    } finally {
      await connection.destroy();
    }
  }

  async createUser(tenantId: string, createUserDto: CreateClinicUserDto): Promise<TenantUser> {
    const connection = await this.getTenantConnection(tenantId);

    try {
      // Check if user already exists in this tenant
      const existingQuery = `SELECT id FROM users WHERE email = $1`;
      const existing = await connection.query(existingQuery, [createUserDto.email]);
      
      if (existing.length > 0) {
        throw new ConflictException('A user with this email already exists in this clinic');
      }

      if (!createUserDto.temporaryPassword) {
        throw new BadRequestException('A temporary password is required when creating a clinic user');
      }

      // Hash password supplied by admin/UI flow
      const password = createUserDto.temporaryPassword;
      const passwordHash = await bcrypt.hash(password, 10);

      const query = `
        INSERT INTO users (email, password_hash, first_name, last_name, role, license_number, specialization, phone, must_change_password)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        RETURNING id, email, first_name, last_name, role, license_number, specialization, phone, is_active, must_change_password, password_changed_at, last_login, created_at, updated_at
      `;

      const result = await connection.query(query, [
        createUserDto.email,
        passwordHash,
        createUserDto.firstName,
        createUserDto.lastName,
        createUserDto.role,
        createUserDto.licenseNumber || null,
        createUserDto.specialization || null,
        createUserDto.phone || null,
        true, // must_change_password = true for all new users
      ]);

      const user = result[0];

      // Sync with master database
      try {
        const masterUser = new TenantUserEntity();
        // Use the ID generated by the tenant database if possible, or let master generate its own UUID?
        // Ideally we want them to match, but they are both UUIDs generated by DB.
        // We can't force the ID easily unless we change the INSERT query to accept an ID or use the same ID generator.
        // For now, let's store the tenant's user ID if possible, or let them diverge (which is bad for mapping).
        // Wait, TenantUserEntity has @PrimaryGeneratedColumn('uuid').
        // If we want to link them, we should probably store the tenant's user ID in a separate column or use the same ID.
        // But since we are just doing analytics/directory, diverging IDs is acceptable for now, 
        // provided we query by email/tenantId when needed.
        // However, for update/delete, we need to know WHICH user to update/delete.
        // TenantUserEntity has 'email' and 'tenantId', which should be unique combination.
        
        masterUser.tenantId = tenantId;
        masterUser.firstName = createUserDto.firstName;
        masterUser.lastName = createUserDto.lastName;
        masterUser.email = createUserDto.email;
        masterUser.passwordHash = passwordHash;
        masterUser.role = createUserDto.role as unknown as UserRole;
        masterUser.phone = createUserDto.phone || '';
        masterUser.licenseNumber = createUserDto.licenseNumber;
        masterUser.specialization = createUserDto.specialization;
        masterUser.status = UserStatus.ACTIVE;
        masterUser.mustChangePassword = true;
        
        await this.tenantUserRepository.save(masterUser);
        this.logger.log(`Synced user ${user.email} to master database`);
      } catch (syncError) {
        this.logger.error(`Failed to sync user to master database: ${syncError.message}`);
        // Continue - don't fail the request
      }

      return {
        id: user.id,
        email: user.email,
        firstName: user.first_name,
        lastName: user.last_name,
        role: user.role,
        licenseNumber: user.license_number,
        specialization: user.specialization,
        phone: user.phone,
        isActive: user.is_active,
        mustChangePassword: user.must_change_password,
        passwordChangedAt: user.password_changed_at,
        lastLogin: user.last_login,
        createdAt: user.created_at,
        updatedAt: user.updated_at,
      };
    } finally {
      await connection.destroy();
    }
  }

  async getTenantUsers(tenantId: string): Promise<TenantUser[]> {
    const connection = await this.getTenantConnection(tenantId);
    
    try {
      const query = `
        SELECT id, email, first_name, last_name, role, license_number, specialization, phone, is_active, must_change_password, password_changed_at, last_login, created_at, updated_at
        FROM users
        WHERE is_active = true
        ORDER BY created_at DESC
      `;

      const result = await connection.query(query);
      
      return result.map(user => ({
        id: user.id,
        email: user.email,
        firstName: user.first_name,
        lastName: user.last_name,
        role: user.role,
        licenseNumber: user.license_number,
        specialization: user.specialization,
        phone: user.phone,
        isActive: user.is_active,
        mustChangePassword: user.must_change_password,
        passwordChangedAt: user.password_changed_at,
        lastLogin: user.last_login,
        createdAt: user.created_at,
        updatedAt: user.updated_at,
      }));
    } catch (error) {
      this.logger.error(`Error querying users for tenant ${tenantId}: ${error.message}`);
      throw error;
    } finally {
      await connection.destroy();
    }
  }

  async changePassword(tenantId: string, userId: string, newPassword: string): Promise<TenantUser> {
    const connection = await this.getTenantConnection(tenantId);

    try {
      const passwordHash = await bcrypt.hash(newPassword, 10);
      
      const query = `
        UPDATE users 
        SET password_hash = $1, must_change_password = false, password_changed_at = NOW(), updated_at = NOW()
        WHERE id = $2
        RETURNING id, email, first_name, last_name, role, license_number, specialization, phone, is_active, must_change_password, password_changed_at, last_login, created_at, updated_at
      `;

      const result = await connection.query(query, [passwordHash, userId]);
      
      if (result.length === 0) {
        throw new NotFoundException('User not found');
      }

      const user = result[0];

      return {
        id: user.id,
        email: user.email,
        firstName: user.first_name,
        lastName: user.last_name,
        role: user.role,
        licenseNumber: user.license_number,
        specialization: user.specialization,
        phone: user.phone,
        isActive: user.is_active,
        mustChangePassword: user.must_change_password,
        passwordChangedAt: user.password_changed_at,
        lastLogin: user.last_login,
        createdAt: user.created_at,
        updatedAt: user.updated_at,
      };
    } finally {
      await connection.destroy();
    }
  }

  async updateUserStatus(tenantId: string, userId: string, isActive: boolean): Promise<TenantUser> {
    const connection = await this.getTenantConnection(tenantId);

    try {
      const query = `
        UPDATE users 
        SET is_active = $1, updated_at = NOW()
        WHERE id = $2
        RETURNING id, email, first_name, last_name, role, license_number, specialization, phone, is_active, must_change_password, password_changed_at, last_login, created_at, updated_at
      `;

      const result = await connection.query(query, [isActive, userId]);
      
      if (result.length === 0) {
        throw new NotFoundException('User not found');
      }

      const user = result[0];

      // Sync to master database
      try {
        const status = isActive ? UserStatus.ACTIVE : UserStatus.INACTIVE;
        await this.tenantUserRepository.update(
          { email: user.email, tenantId },
          { status }
        );
        this.logger.log(`Synced user status update for ${user.email} to master database`);
      } catch (error) {
        this.logger.error(`Failed to sync user status update to master database: ${error.message}`);
      }

      return {
        id: user.id,
        email: user.email,
        firstName: user.first_name,
        lastName: user.last_name,
        role: user.role,
        licenseNumber: user.license_number,
        specialization: user.specialization,
        phone: user.phone,
        isActive: user.is_active,
        mustChangePassword: user.must_change_password,
        passwordChangedAt: user.password_changed_at,
        lastLogin: user.last_login,
        createdAt: user.created_at,
        updatedAt: user.updated_at,
      };
    } finally {
      await connection.destroy();
    }
  }

  async resetPassword(tenantId: string, userId: string): Promise<{ user: TenantUser; temporaryPassword: string }> {
    const connection = await this.getTenantConnection(tenantId);

    try {
      // Generate a cryptographically strong temporary password.
      const tempPassword = randomBytes(12).toString('base64url').slice(0, 16);
      const passwordHash = await bcrypt.hash(tempPassword, 10);
      
      const query = `
        UPDATE users 
        SET password_hash = $1, must_change_password = true, password_changed_at = NULL, updated_at = NOW()
        WHERE id = $2
        RETURNING id, email, first_name, last_name, role, license_number, specialization, phone, is_active, must_change_password, password_changed_at, last_login, created_at, updated_at
      `;

      const result = await connection.query(query, [passwordHash, userId]);
      
      if (result.length === 0) {
        throw new NotFoundException('User not found');
      }

      const user = result[0];
      
      return {
        user: {
          id: user.id,
          email: user.email,
          firstName: user.first_name,
          lastName: user.last_name,
          role: user.role,
          licenseNumber: user.license_number,
          specialization: user.specialization,
          phone: user.phone,
          isActive: user.is_active,
          mustChangePassword: user.must_change_password,
          passwordChangedAt: user.password_changed_at,
          lastLogin: user.last_login,
          createdAt: user.created_at,
          updatedAt: user.updated_at,
        },
        temporaryPassword: tempPassword,
      };
    } finally {
      await connection.destroy();
    }
  }

  async deleteUser(tenantId: string, userId: string): Promise<void> {
    const connection = await this.getTenantConnection(tenantId);

    try {
      // RETURNING email to allow sync
      const query = `UPDATE users SET is_active = false, updated_at = NOW() WHERE id = $1 RETURNING email`;
      const result = await connection.query(query, [userId]);
      
      // Check if any row was returned (result is array of rows)
      if (result.length === 0) {
        throw new NotFoundException('User not found');
      }

      // Sync to master database
      try {
        const email = result[0].email;
        await this.tenantUserRepository.update(
          { email, tenantId },
          { status: UserStatus.INACTIVE } // Soft delete in master
        );
        this.logger.log(`Synced user deletion (soft) for ${email} to master database`);
      } catch (error) {
        this.logger.error(`Failed to sync user deletion to master database: ${error.message}`);
      }
    } finally {
      await connection.destroy();
    }
  }


}
