FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Expose port
EXPOSE 3015

# Start development server
CMD ["npm", "start"]

