#!/usr/bin/env node
/*
  MOAS-23 (B-001): safe, resettable seed/v1 for the e2e-clinic synthetic
  tenant. `seed-audit-v1.js` is purely additive (creates more patients every
  run); this script is the missing "reset" half — it deletes every entity
  the current seed/v1/manifest.json recorded (by id, read back from the
  manifest itself, never a blanket table wipe) and removes the manifest, so
  the tenant can be returned to a clean synthetic-data-free state before a
  fresh seed run. All identities are synthetic (Zimbabwean placeholder
  names/national-IDs generated by seed-audit-v1.js) — there is no real PHI
  in this tenant to protect against.

  Usage:
    node scripts/seed-reset.mjs            # reset only
    node scripts/seed-reset.mjs --reseed   # reset, then re-run seed-audit-v1.js
*/
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const EHR_API_URL = process.env.EHR_API_URL || 'http://localhost:3013/api';
const TENANT_ID = process.env.TENANT_ID || 'e2e-clinic';
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@e2e-clinic.com';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'Umoya1#';
const MANIFEST_PATH = path.resolve(process.cwd(), 'seed', 'v1', 'manifest.json');

async function login() {
  const res = await fetch(`${EHR_API_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Tenant-ID': TENANT_ID },
    body: JSON.stringify({ email: ADMIN_EMAIL, password: ADMIN_PASSWORD }),
  });
  const data = await res.json();
  if (!data.token) throw new Error(`Admin login failed: ${JSON.stringify(data)}`);
  return data.token;
}

async function deleteEntity(token, path, id) {
  const res = await fetch(`${EHR_API_URL}${path}/${id}`, {
    method: 'DELETE',
    headers: { 'X-Tenant-ID': TENANT_ID, Authorization: `Bearer ${token}` },
  });
  return res.status;
}

async function main() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    console.log('No seed/v1/manifest.json found — nothing to reset.');
  } else {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
    const token = await login();

    const patientIds = [
      ...(manifest.patients || []).map((p) => p.id),
      ...(manifest.nearDuplicatePairs || []).map((p) => p.duplicateId).filter(Boolean),
    ];
    let patientsDeleted = 0;
    let patientErrors = 0;
    for (const id of patientIds) {
      const status = await deleteEntity(token, '/patients', id);
      if (status >= 200 && status < 300) patientsDeleted += 1;
      else patientErrors += 1;
    }
    console.log(`Patients: ${patientsDeleted} deleted, ${patientErrors} errors (of ${patientIds.length} tracked).`);

    const clinicianIds = (manifest.clinicians || []).map((c) => c.id).filter(Boolean);
    let cliniciansDeleted = 0;
    let clinicianErrors = 0;
    for (const id of clinicianIds) {
      const status = await deleteEntity(token, '/users', id);
      if (status >= 200 && status < 300) cliniciansDeleted += 1;
      else clinicianErrors += 1;
    }
    console.log(`Clinicians: ${cliniciansDeleted} deleted, ${clinicianErrors} errors (of ${clinicianIds.length} tracked).`);

    fs.unlinkSync(MANIFEST_PATH);
    console.log('Removed seed/v1/manifest.json.');
  }

  if (process.argv.includes('--reseed')) {
    console.log('\nRe-seeding...');
    execSync('node scripts/seed-audit-v1.js', { stdio: 'inherit', cwd: process.cwd() });
  }
}

main().catch((err) => {
  console.error('Seed reset failed:', err.message);
  process.exit(1);
});
