#!/bin/bash

# Load environment variables
source "$(dirname "$0")/load-env.sh"
echo "🧪 Testing Tier 1 Endpoints (No Auth)"
echo "======================================"
echo ""
echo "Testing consent templates..."
curl -s -o /dev/null -w "GET /api/consents/templates: HTTP %{http_code}\n" "$API_BASE_URL/consents/templates"
echo ""
echo "Testing immunization schedules..."
curl -s -o /dev/null -w "GET /api/immunizations/schedules: HTTP %{http_code}\n" "$API_BASE_URL/immunizations/schedules"
echo ""
echo "Testing clinical pathways..."
curl -s -o /dev/null -w "GET /api/clinical-pathways: HTTP %{http_code}\n" "$API_BASE_URL/clinical-pathways"
echo ""
echo "Testing beds..."
curl -s -o /dev/null -w "GET /api/beds: HTTP %{http_code}\n" "$API_BASE_URL/beds"
echo ""
echo "Testing ED tracking board..."
curl -s -o /dev/null -w "GET /api/ed/tracking-board: HTTP %{http_code}\n" "$API_BASE_URL/ed/tracking-board"
echo ""
echo "Testing ED metrics..."
curl -s -o /dev/null -w "GET /api/ed/metrics: HTTP %{http_code}\n" "$API_BASE_URL/ed/metrics"
echo ""
echo "Expected: HTTP 401 (Unauthorized - means endpoint exists!)"
echo "If 404: Endpoint doesn't exist (problem)"
