apiVersion: 1
datasources:
  - name: PostgreSQL-MediCore
    type: postgres
    url: postgres-master:5432
    database: medicore_production
    user: ${GRAFANA_DB_USER:-medicore}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD:-medicore_password}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: false

  - name: Prometheus
    type: prometheus
    url: http://medicore-prometheus:9090
    access: proxy
    editable: false
